<?php

namespace Database\Seeders;

use App\Models\NotificationScreen;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NotificationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
          // Combined permissions from both arrays
          $notifications = [
            ['name' => 'Quotation Create', 'screen' => 'Quotation', 'action' => 'Create'],
            ['name' => 'Quotation Verify', 'screen' => 'Quotation', 'action' => 'Verify'],
            ['name' => 'Order Create', 'screen' => 'Order', 'action' => 'Create'],
            ['name' => 'Category List', 'screen' => 'Category', 'action' => 'List'],
            ['name' => 'Category Create', 'screen' => 'Category', 'action' => 'Create'],
            ['name' => 'Category Edit', 'screen' => 'Category', 'action' => 'Edit'],
            ['name' => 'Category View', 'screen' => 'Category', 'action' => 'View'],
            ['name' => 'Category Delete', 'screen' => 'Category', 'action' => 'Delete'],
            ['name' => 'Sales Price List', 'screen' => 'Sales Price', 'action' => 'List'],
            ['name' => 'Sales Price Create', 'screen' => 'Sales Price', 'action' => 'Create'],
            ['name' => 'Sales Price Edit', 'screen' => 'Sales Price', 'action' => 'Edit'],
            ['name' => 'Sales Price Verify', 'screen' => 'Sales Price', 'action' => 'Verify'],
            ['name' => 'Sales Price View', 'screen' => 'Sales Price', 'action' => 'View'],
            ['name' => 'Sales Price Delete', 'screen' => 'Sales Price', 'action' => 'Delete'],
            ['name' => 'Invoice List', 'screen' => 'Invoice', 'action' => 'List'],
            ['name' => 'Invoice Create', 'screen' => 'Invoice', 'action' => 'Create'],
            ['name' => 'Invoice Edit', 'screen' => 'Invoice', 'action' => 'Edit'],
            ['name' => 'Invoice View', 'screen' => 'Invoice', 'action' => 'View'],
            ['name' => 'Invoice Preview', 'screen' => 'Invoice', 'action' => 'Preview'],
            ['name' => 'Invoice Delete', 'screen' => 'Invoice', 'action' => 'Delete'],
            ['name' => 'Machine Status View', 'screen' => 'Machine Status', 'action' => 'View'],
            ['name' => 'Shopfloor View', 'screen' => 'Shopfloor', 'action' => 'View'],
            ['name' => 'Production Output Traceability List', 'screen' => 'Production Output Traceability', 'action' => 'List'],
            ['name' => 'Production Output Traceability Edit', 'screen' => 'Production Output Traceability', 'action' => 'Edit'],
            ['name' => 'Production Output Traceability QC', 'screen' => 'Production Output Traceability', 'action' => 'QC'],
            ['name' => 'Production Output Traceability View', 'screen' => 'Production Output Traceability', 'action' => 'View'],
            ['name' => 'Summary Report View', 'screen' => 'Summary Report', 'action' => 'View'],
            ['name' => 'Call For Assistance List', 'screen' => 'Call For Assistance', 'action' => 'List'],
            ['name' => 'Call For Assistance Update', 'screen' => 'Call For Assistance', 'action' => 'Update'],
            ['name' => 'Call For Assistance View', 'screen' => 'Call For Assistance', 'action' => 'View'],
            ['name' => 'OEE Report View', 'screen' => 'OEE Report', 'action' => 'View'],
            ['name' => 'Inventory Shopfloor View', 'screen' => 'Inventory Shopfloor', 'action' => 'View'],
            ['name' => 'Inventory Dashboard View', 'screen' => 'Inventory Dashboard', 'action' => 'View'],
            ['name' => 'Good Receiving List', 'screen' => 'Good Receiving', 'action' => 'List'],
            ['name' => 'Good Receiving Create', 'screen' => 'Good Receiving', 'action' => 'Create'],
            ['name' => 'Good Receiving Edit', 'screen' => 'Good Receiving', 'action' => 'Edit'],
            ['name' => 'Good Receiving Receive', 'screen' => 'Good Receiving', 'action' => 'Receive'],
            ['name' => 'Good Receiving QC', 'screen' => 'Good Receiving', 'action' => 'QC'],
            ['name' => 'Good Receiving Approve', 'screen' => 'Good Receiving', 'action' => 'Approve'],
            ['name' => 'Good Receiving Allocation', 'screen' => 'Good Receiving', 'action' => 'Allocation'],
            ['name' => 'Good Receiving View', 'screen' => 'Good Receiving', 'action' => 'View'],
            ['name' => 'Good Receiving Delete', 'screen' => 'Good Receiving', 'action' => 'Delete'],
            ['name' => 'Delivery Instruction List', 'screen' => 'Delivery Instruction', 'action' => 'List'],
            ['name' => 'Delivery Instruction Create', 'screen' => 'Delivery Instruction', 'action' => 'Create'],
            ['name' => 'Delivery Instruction Edit', 'screen' => 'Delivery Instruction', 'action' => 'Edit'],
            ['name' => 'Delivery Instruction View', 'screen' => 'Delivery Instruction', 'action' => 'View'],
            ['name' => 'Delivery Instruction Delete', 'screen' => 'Delivery Instruction', 'action' => 'Delete'],
            ['name' => 'Stock Adjustment List', 'screen' => 'Stock Adjustment', 'action' => 'List'],
            ['name' => 'Stock Adjustment Update', 'screen' => 'Stock Adjustment', 'action' => 'Update'],
            ['name' => 'Stock Relocation List', 'screen' => 'Stock Relocation', 'action' => 'List'],
            ['name' => 'Stock Relocation Create', 'screen' => 'Stock Relocation', 'action' => 'Create'],
            ['name' => 'Stock Relocation Edit', 'screen' => 'Stock Relocation', 'action' => 'Edit'],
            ['name' => 'Stock Relocation View', 'screen' => 'Stock Relocation', 'action' => 'View'],
            ['name' => 'Stock Relocation Delete', 'screen' => 'Stock Relocation', 'action' => 'Delete'],
            ['name' => 'Product Reordering List', 'screen' => 'Product Reordering', 'action' => 'List'],
            ['name' => 'Product Reordering Create', 'screen' => 'Product Reordering', 'action' => 'Create'],
            ['name' => 'Product Reordering Edit', 'screen' => 'Product Reordering', 'action' => 'Edit'],
            ['name' => 'Product Reordering View', 'screen' => 'Product Reordering', 'action' => 'View'],
            ['name' => 'Product Reordering Delete', 'screen' => 'Product Reordering', 'action' => 'Delete'],
            ['name' => 'Outgoing List', 'screen' => 'Outgoing', 'action' => 'List'],
            ['name' => 'Outgoing Create', 'screen' => 'Outgoing', 'action' => 'Create'],
            ['name' => 'Outgoing Edit', 'screen' => 'Outgoing', 'action' => 'Edit'],
            ['name' => 'Outgoing View', 'screen' => 'Outgoing', 'action' => 'View'],
            ['name' => 'Outgoing Preview', 'screen' => 'Outgoing', 'action' => 'Preview'],
            ['name' => 'Outgoing Delete', 'screen' => 'Outgoing', 'action' => 'Delete'],
            ['name' => 'Sales Return List', 'screen' => 'Sales Return', 'action' => 'List'],
            ['name' => 'Sales Return Create', 'screen' => 'Sales Return', 'action' => 'Create'],
            ['name' => 'Sales Return Edit', 'screen' => 'Sales Return', 'action' => 'Edit'],
            ['name' => 'Sales Return View', 'screen' => 'Sales Return', 'action' => 'View'],
            ['name' => 'Sales Return Delete', 'screen' => 'Sales Return', 'action' => 'Delete'],
            ['name' => 'Purchase Return List', 'screen' => 'Purchase Return', 'action' => 'List'],
            ['name' => 'Purchase Return Create', 'screen' => 'Purchase Return', 'action' => 'Create'],
            ['name' => 'Purchase Return Edit', 'screen' => 'Purchase Return', 'action' => 'Edit'],
            ['name' => 'Purchase Return View', 'screen' => 'Purchase Return', 'action' => 'View'],
            ['name' => 'Purchase Return Preview', 'screen' => 'Purchase Return', 'action' => 'Preview'],
            ['name' => 'Purchase Return QC', 'screen' => 'Purchase Return', 'action' => 'QC'],
            ['name' => 'Purchase Return Receive', 'screen' => 'Purchase Return', 'action' => 'Receive'],
            ['name' => 'Purchase Return Delete', 'screen' => 'Purchase Return', 'action' => 'Delete'],
            ['name' => 'Inventory Report View', 'screen' => 'Inventory Report', 'action' => 'View'],
            ['name' => 'Stock Card Report View', 'screen' => 'Stock Card Report', 'action' => 'View'],
            ['name' => 'Summary DO Report View', 'screen' => 'Summary DO Report', 'action' => 'View'],
            ['name' => 'Type Of Rejection List', 'screen' => 'Type Of Rejection', 'action' => 'List'],
            ['name' => 'Type Of Rejection Create', 'screen' => 'Type Of Rejection', 'action' => 'Create'],
            ['name' => 'Type Of Rejection Edit', 'screen' => 'Type Of Rejection', 'action' => 'Edit'],
            ['name' => 'Type Of Rejection View', 'screen' => 'Type Of Rejection', 'action' => 'View'],
            ['name' => 'Type Of Rejection Delete', 'screen' => 'Type Of Rejection', 'action' => 'Delete'],
            ['name' => 'Type Of Product List', 'screen' => 'Type Of Product', 'action' => 'List'],
            ['name' => 'Type Of Product Create', 'screen' => 'Type Of Product', 'action' => 'Create'],
            ['name' => 'Type Of Product Edit', 'screen' => 'Type Of Product', 'action' => 'Edit'],
            ['name' => 'Type Of Product View', 'screen' => 'Type Of Product', 'action' => 'View'],
            ['name' => 'Type Of Product Delete', 'screen' => 'Type Of Product', 'action' => 'Delete'],
            ['name' => 'Machine Tonnage List', 'screen' => 'Machine Tonnage', 'action' => 'List'],
            ['name' => 'Machine Tonnage Create', 'screen' => 'Machine Tonnage', 'action' => 'Create'],
            ['name' => 'Machine Tonnage Edit', 'screen' => 'Machine Tonnage', 'action' => 'Edit'],
            ['name' => 'Machine Tonnage View', 'screen' => 'Machine Tonnage', 'action' => 'View'],
            ['name' => 'Machine Tonnage Delete', 'screen' => 'Machine Tonnage', 'action' => 'Delete'],
            ['name' => 'Machine List', 'screen' => 'Machine', 'action' => 'List'],
            ['name' => 'Machine Create', 'screen' => 'Machine', 'action' => 'Create'],
            ['name' => 'Machine Edit', 'screen' => 'Machine', 'action' => 'Edit'],
            ['name' => 'Machine View', 'screen' => 'Machine', 'action' => 'View'],
            ['name' => 'Machine Delete', 'screen' => 'Machine', 'action' => 'Delete'],
            ['name' => 'Area List', 'screen' => 'Area', 'action' => 'List'],
            ['name' => 'Area Create', 'screen' => 'Area', 'action' => 'Create'],
            ['name' => 'Area Edit', 'screen' => 'Area', 'action' => 'Edit'],
            ['name' => 'Area View', 'screen' => 'Area', 'action' => 'View'],
            ['name' => 'Area Delete', 'screen' => 'Area', 'action' => 'Delete'],
            ['name' => 'Area Rack List', 'screen' => 'Area Rack', 'action' => 'List'],
            ['name' => 'Area Rack Create', 'screen' => 'Area Rack', 'action' => 'Create'],
            ['name' => 'Area Rack Edit', 'screen' => 'Area Rack', 'action' => 'Edit'],
            ['name' => 'Area Rack View', 'screen' => 'Area Rack', 'action' => 'View'],
            ['name' => 'Area Rack Delete', 'screen' => 'Area Rack', 'action' => 'Delete'],
            ['name' => 'Area Level List', 'screen' => 'Area Level', 'action' => 'List'],
            ['name' => 'Area Level Create', 'screen' => 'Area Level', 'action' => 'Create'],
            ['name' => 'Area Level Edit', 'screen' => 'Area Level', 'action' => 'Edit'],
            ['name' => 'Area Level View', 'screen' => 'Area Level', 'action' => 'View'],
            ['name' => 'Area Level Delete', 'screen' => 'Area Level', 'action' => 'Delete'],
            ['name' => 'Unit List', 'screen' => 'Unit', 'action' => 'List'],
            ['name' => 'Unit Create', 'screen' => 'Unit', 'action' => 'Create'],
            ['name' => 'Unit Edit', 'screen' => 'Unit', 'action' => 'Edit'],
            ['name' => 'Unit View', 'screen' => 'Unit', 'action' => 'View'],
            ['name' => 'Unit Delete', 'screen' => 'Unit', 'action' => 'Delete'],
            ['name' => 'Process List', 'screen' => 'Process', 'action' => 'List'],
            ['name' => 'Process Create', 'screen' => 'Process', 'action' => 'Create'],
            ['name' => 'Process Edit', 'screen' => 'Process', 'action' => 'Edit'],
            ['name' => 'Process View', 'screen' => 'Process', 'action' => 'View'],
            ['name' => 'Process Delete', 'screen' => 'Process', 'action' => 'Delete'],
            ['name' => 'Customer List', 'screen' => 'Customer', 'action' => 'List'],
            ['name' => 'Customer Create', 'screen' => 'Customer', 'action' => 'Create'],
            ['name' => 'Customer Edit', 'screen' => 'Customer', 'action' => 'Edit'],
            ['name' => 'Customer View', 'screen' => 'Customer', 'action' => 'View'],
            ['name' => 'Customer Delete', 'screen' => 'Customer', 'action' => 'Delete'],
            ['name' => 'Supplier List', 'screen' => 'Supplier', 'action' => 'List'],
            ['name' => 'Supplier Create', 'screen' => 'Supplier', 'action' => 'Create'],
            ['name' => 'Supplier Edit', 'screen' => 'Supplier', 'action' => 'Edit'],
            ['name' => 'Supplier View', 'screen' => 'Supplier', 'action' => 'View'],
            ['name' => 'Supplier Delete', 'screen' => 'Supplier', 'action' => 'Delete'],
            ['name' => 'Product List', 'screen' => 'Product', 'action' => 'List'],
            ['name' => 'Product Create', 'screen' => 'Product', 'action' => 'Create'],
            ['name' => 'Product Edit', 'screen' => 'Product', 'action' => 'Edit'],
            ['name' => 'Product View', 'screen' => 'Product', 'action' => 'View'],
            ['name' => 'Product Delete', 'screen' => 'Product', 'action' => 'Delete'],
            ['name' => 'Product Amortization Edit', 'screen' => 'Product Amortization', 'action' => 'Edit'],
            ['name' => 'Department List', 'screen' => 'Department', 'action' => 'List'],
            ['name' => 'Department Create', 'screen' => 'Department', 'action' => 'Create'],
            ['name' => 'Department Edit', 'screen' => 'Department', 'action' => 'Edit'],
            ['name' => 'Department View', 'screen' => 'Department', 'action' => 'View'],
            ['name' => 'Department Delete', 'screen' => 'Department', 'action' => 'Delete'],
            ['name' => 'Designation List', 'screen' => 'Designation', 'action' => 'List'],
            ['name' => 'Designation Create', 'screen' => 'Designation', 'action' => 'Create'],
            ['name' => 'Designation Edit', 'screen' => 'Designation', 'action' => 'Edit'],
            ['name' => 'Designation View', 'screen' => 'Designation', 'action' => 'View'],
            ['name' => 'Designation Delete', 'screen' => 'Designation', 'action' => 'Delete'],
            ['name' => 'Role List', 'screen' => 'Role', 'action' => 'List'],
            ['name' => 'Role Create', 'screen' => 'Role', 'action' => 'Create'],
            ['name' => 'Role Edit', 'screen' => 'Role', 'action' => 'Edit'],
            ['name' => 'Role View', 'screen' => 'Role', 'action' => 'View'],
            ['name' => 'Role Delete', 'screen' => 'Role', 'action' => 'Delete'],
            ['name' => 'User List', 'screen' => 'User', 'action' => 'List'],
            ['name' => 'User Create', 'screen' => 'User', 'action' => 'Create'],
            ['name' => 'User Edit', 'screen' => 'User', 'action' => 'Edit'],
            ['name' => 'User View', 'screen' => 'User', 'action' => 'View'],
            ['name' => 'User Delete', 'screen' => 'User', 'action' => 'Delete'],
            ['name' => 'Leave List', 'screen' => 'Leave', 'action' => 'List'],
            ['name' => 'Leave Create', 'screen' => 'Leave', 'action' => 'Create'],
            ['name' => 'Leave Edit', 'screen' => 'Leave', 'action' => 'Edit'],
            ['name' => 'Leave View', 'screen' => 'Leave', 'action' => 'View'],
            ['name' => 'Leave Manage', 'screen' => 'Leave', 'action' => 'Manage'],
            ['name' => 'Leave Delete', 'screen' => 'Leave', 'action' => 'Delete'],
            ['name' => 'General Settings SST Percentage', 'screen' => 'General Settings', 'action' => 'SST Percentage'],
            ['name' => 'General Settings PO Important Note', 'screen' => 'General Settings', 'action' => 'PO Important Note'],
            ['name' => 'General Settings Spec Break', 'screen' => 'General Settings', 'action' => 'Spec Break'],
            ['name' => 'General Settings Initial Ref No', 'screen' => 'General Settings', 'action' => 'Initial Ref No'],
            ['name' => 'General Settings PR Approval', 'screen' => 'General Settings', 'action' => 'PR Approval'],
            ['name' => 'Purchase Price List', 'screen' => 'Purchase Price', 'action' => 'List'],
            ['name' => 'Purchase Price Create', 'screen' => 'Purchase Price', 'action' => 'Create'],
            ['name' => 'Purchase Price Edit', 'screen' => 'Purchase Price', 'action' => 'Edit'],
            ['name' => 'Purchase Price Verify', 'screen' => 'Purchase Price', 'action' => 'Verify'],
            ['name' => 'Purchase Price View', 'screen' => 'Purchase Price', 'action' => 'View'],
            ['name' => 'Purchase Price Delete', 'screen' => 'Purchase Price', 'action' => 'Delete'],
            ['name' => 'Purchase Requisition List', 'screen' => 'Purchase Requisition', 'action' => 'List'],
            ['name' => 'Purchase Requisition Create', 'screen' => 'Purchase Requisition', 'action' => 'Create'],
            ['name' => 'Purchase Requisition Edit', 'screen' => 'Purchase Requisition', 'action' => 'Edit'],
            ['name' => 'Purchase Requisition View', 'screen' => 'Purchase Requisition', 'action' => 'View'],
            ['name' => 'Purchase Requisition Delete', 'screen' => 'Purchase Requisition', 'action' => 'Delete'],
            ['name' => 'Purchase Requisition Verify HOD', 'screen' => 'Purchase Requisition', 'action' => 'Verify HOD'],
            ['name' => 'Purchase Requisition Verify ACC', 'screen' => 'Purchase Requisition', 'action' => 'Verify ACC'],
            ['name' => 'Purchase Requisition Approve', 'screen' => 'Purchase Requisition', 'action' => 'Approve'],
            ['name' => 'Purchase Requisition Decline', 'screen' => 'Purchase Requisition', 'action' => 'Decline'],
            ['name' => 'Purchase Requisition Cancel', 'screen' => 'Purchase Requisition', 'action' => 'Cancel'],
            ['name' => 'Purchase Planning List', 'screen' => 'Purchase Planning', 'action' => 'List'],
            ['name' => 'Purchase Planning Create', 'screen' => 'Purchase Planning', 'action' => 'Create'],
            ['name' => 'Purchase Planning Edit', 'screen' => 'Purchase Planning', 'action' => 'Edit'],
            ['name' => 'Purchase Planning View', 'screen' => 'Purchase Planning', 'action' => 'View'],
            ['name' => 'Purchase Planning Delete', 'screen' => 'Purchase Planning', 'action' => 'Delete'],
            ['name' => 'Purchase Planning Verify HOD', 'screen' => 'Purchase Planning', 'action' => 'Verify HOD'],
            ['name' => 'Purchase Planning Verify ACC', 'screen' => 'Purchase Planning', 'action' => 'Verify ACC'],
            ['name' => 'Purchase Planning Approve', 'screen' => 'Purchase Planning', 'action' => 'Approve'],
            ['name' => 'Purchase Planning Check', 'screen' => 'Purchase Planning', 'action' => 'Check'],
            ['name' => 'Purchase Planning Decline', 'screen' => 'Purchase Planning', 'action' => 'Decline'],
            ['name' => 'Purchase Planning Cancel', 'screen' => 'Purchase Planning', 'action' => 'Cancel'],
            ['name' => 'Purchase Order List', 'screen' => 'Purchase Order', 'action' => 'List'],
            ['name' => 'Purchase Order Create', 'screen' => 'Purchase Order', 'action' => 'Create'],
            ['name' => 'Purchase Order Edit', 'screen' => 'Purchase Order', 'action' => 'Edit'],
            ['name' => 'Purchase Order View', 'screen' => 'Purchase Order', 'action' => 'View'],
            ['name' => 'Purchase Order Preview', 'screen' => 'Purchase Order', 'action' => 'Preview'],
            ['name' => 'Purchase Order Delete', 'screen' => 'Purchase Order', 'action' => 'Delete'],
            ['name' => 'Purchase Order Verify', 'screen' => 'Purchase Order', 'action' => 'Verify'],
            ['name' => 'Purchase Order Check', 'screen' => 'Purchase Order', 'action' => 'Check'],
            ['name' => 'Purchase Order Decline', 'screen' => 'Purchase Order', 'action' => 'Decline'],
            ['name' => 'Purchase Order Cancel', 'screen' => 'Purchase Order', 'action' => 'Cancel'],
            ['name' => 'Supplier Ranking List', 'screen' => 'Supplier Ranking', 'action' => 'List'],
            ['name' => 'Supplier Ranking Create', 'screen' => 'Supplier Ranking', 'action' => 'Create'],
            ['name' => 'Supplier Ranking Edit', 'screen' => 'Supplier Ranking', 'action' => 'Edit'],
            ['name' => 'Supplier Ranking View', 'screen' => 'Supplier Ranking', 'action' => 'View'],
            ['name' => 'Supplier Ranking Delete', 'screen' => 'Supplier Ranking', 'action' => 'Delete'],
            ['name' => 'BOM List', 'screen' => 'BOM', 'action' => 'List'],
            ['name' => 'BOM Create', 'screen' => 'BOM', 'action' => 'Create'],
            ['name' => 'BOM Edit', 'screen' => 'BOM', 'action' => 'Edit'],
            ['name' => 'BOM View', 'screen' => 'BOM', 'action' => 'View'],
            ['name' => 'BOM Delete', 'screen' => 'BOM', 'action' => 'Delete'],
            ['name' => 'BOM Verification', 'screen' => 'BOM', 'action' => 'Verification'],
            ['name' => 'BOM Verify', 'screen' => 'BOM', 'action' => 'Verify'],
            ['name' => 'BOM Decline', 'screen' => 'BOM', 'action' => 'Decline'],
            ['name' => 'BOM Cancel', 'screen' => 'BOM', 'action' => 'Cancel'],
            ['name' => 'BOM Inactive', 'screen' => 'BOM', 'action' => 'Inactive'],
            ['name' => 'BOM Report', 'screen' => 'BOM', 'action' => 'Report'],
            ['name' => 'Daily Production Planning List', 'screen' => 'Daily Production Planning', 'action' => 'List'],
            ['name' => 'Daily Production Planning Create', 'screen' => 'Daily Production Planning', 'action' => 'Create'],
            ['name' => 'Daily Production Planning Edit', 'screen' => 'Daily Production Planning', 'action' => 'Edit'],
            ['name' => 'Daily Production Planning View', 'screen' => 'Daily Production Planning', 'action' => 'View'],
            ['name' => 'Daily Production Planning Delete', 'screen' => 'Daily Production Planning', 'action' => 'Delete'],
            ['name' => 'Monthly Production Planning', 'screen' => 'Monthly Production Planning', 'action' => 'List'],
            ['name' => 'Production Scheduling View', 'screen' => 'Production Scheduling', 'action' => 'View'],
            ['name' => 'Material Requisition List', 'screen' => 'Material Requisition', 'action' => 'List'],
            ['name' => 'Material Requisition Create', 'screen' => 'Material Requisition', 'action' => 'Create'],
            ['name' => 'Material Requisition Edit', 'screen' => 'Material Requisition', 'action' => 'Edit'],
            ['name' => 'Material Requisition View', 'screen' => 'Material Requisition', 'action' => 'View'],
            ['name' => 'Material Requisition Delete', 'screen' => 'Material Requisition', 'action' => 'Delete'],
            ['name' => 'Material Requisition Issue', 'screen' => 'Material Requisition', 'action' => 'Issue'],
            ['name' => 'Material Requisition Receive', 'screen' => 'Material Requisition', 'action' => 'Receive'],
            ['name' => 'Transfer Request List', 'screen' => 'Transfer Request', 'action' => 'List'],
            ['name' => 'Transfer Request Create', 'screen' => 'Transfer Request', 'action' => 'Create'],
            ['name' => 'Transfer Request Edit', 'screen' => 'Transfer Request', 'action' => 'Edit'],
            ['name' => 'Transfer Request View', 'screen' => 'Transfer Request', 'action' => 'View'],
            ['name' => 'Transfer Request Delete', 'screen' => 'Transfer Request', 'action' => 'Delete'],
            ['name' => 'Transfer Request Issue', 'screen' => 'Transfer Request', 'action' => 'Issue'],
            ['name' => 'Transfer Request Receive', 'screen' => 'Transfer Request', 'action' => 'Receive'],
            ['name' => 'Transfer Request QC', 'screen' => 'Transfer Request', 'action' => 'QC'],
            ['name' => 'Discrepancy List', 'screen' => 'Discrepancy', 'action' => 'List'],
            ['name' => 'Discrepancy Edit', 'screen' => 'Discrepancy', 'action' => 'Edit'],
            ['name' => 'Discrepancy View', 'screen' => 'Discrepancy', 'action' => 'View'],
            ['name' => 'Attendance List', 'screen' => 'Attendance', 'action' => 'List'],
            ['name' => 'Attendance Import', 'screen' => 'Attendance', 'action' => 'Import'],
            ['name' => 'Attendance Export', 'screen' => 'Attendance', 'action' => 'Export'],
            ['name' => 'General Settings Payroll Setup', 'screen' => 'General Settings', 'action' => 'Payroll Setup'],
            ['name' => 'products-index', 'screen' => 'Products', 'action' => 'Index'],
    ['name' => 'purchases-index', 'screen' => 'Purchases', 'action' => 'Index'],
    ['name' => 'purchase-payment-index', 'screen' => 'Purchase Payment', 'action' => 'Index'],
    ['name' => 'purchase-payment-add', 'screen' => 'Purchase Payment', 'action' => 'Add'],
    ['name' => 'purchase-payment-edit', 'screen' => 'Purchase Payment', 'action' => 'Edit'],
    ['name' => 'purchase-payment-delete', 'screen' => 'Purchase Payment', 'action' => 'Delete'],
    ['name' => 'sales-index', 'screen' => 'Sales', 'action' => 'Index'],
    ['name' => 'sale-payment-index', 'screen' => 'Sale Payment', 'action' => 'Index'],
    ['name' => 'sale-payment-add', 'screen' => 'Sale Payment', 'action' => 'Add'],
    ['name' => 'sale-payment-edit', 'screen' => 'Sale Payment', 'action' => 'Edit'],
    ['name' => 'sale-payment-delete', 'screen' => 'Sale Payment', 'action' => 'Delete'],
    ['name' => 'expenses-index', 'screen' => 'Expenses', 'action' => 'Index'],
    ['name' => 'expenses-add', 'screen' => 'Expenses', 'action' => 'Add'],
    ['name' => 'expenses-edit', 'screen' => 'Expenses', 'action' => 'Edit'],
    ['name' => 'expenses-delete', 'screen' => 'Expenses', 'action' => 'Delete'],
    ['name' => 'incomes-index', 'screen' => 'Incomes', 'action' => 'Index'],
    ['name' => 'incomes-add', 'screen' => 'Incomes', 'action' => 'Add'],
    ['name' => 'incomes-edit', 'screen' => 'Incomes', 'action' => 'Edit'],
    ['name' => 'incomes-delete', 'screen' => 'Incomes', 'action' => 'Delete'],
    ['name' => 'quotes-index', 'screen' => 'Quotes', 'action' => 'Index'],
    ['name' => 'transfers-index', 'screen' => 'Transfers', 'action' => 'Index'],
    ['name' => 'returns-index', 'screen' => 'Returns', 'action' => 'Index'],
    ['name' => 'purchase-return-index', 'screen' => 'Purchase Return', 'action' => 'Index'],
    ['name' => 'employees-index', 'screen' => 'Employees', 'action' => 'Index'],
    ['name' => 'users-index', 'screen' => 'Users', 'action' => 'Index'],
    ['name' => 'customers-index', 'screen' => 'Customers', 'action' => 'Index'],
    ['name' => 'suppliers-index', 'screen' => 'Suppliers', 'action' => 'Index'],
    ['name' => 'revenue_profit_summary', 'screen' => 'Reports', 'action' => 'Revenue Profit Summary'],
    ['name' => 'cash_flow', 'screen' => 'Reports', 'action' => 'Cash Flow'],
    ['name' => 'monthly_summary', 'screen' => 'Reports', 'action' => 'Monthly Summary'],
    ['name' => 'yearly_report', 'screen' => 'Reports', 'action' => 'Yearly Report'],
    ['name' => 'account-index', 'screen' => 'Account', 'action' => 'Index'],
    ['name' => 'money-transfer', 'screen' => 'Account', 'action' => 'Money Transfer'],
    ['name' => 'balance-sheet', 'screen' => 'Account', 'action' => 'Balance Sheet'],
    ['name' => 'account-statement', 'screen' => 'Account', 'action' => 'Statement'],
    ['name' => 'department', 'screen' => 'Department', 'action' => 'Index'],
    ['name' => 'attendance', 'screen' => 'Attendance', 'action' => 'Index'],
    ['name' => 'profit-loss', 'screen' => 'Reports', 'action' => 'Profit Loss'],
    ['name' => 'best-seller', 'screen' => 'Reports', 'action' => 'Best Seller'],
    ['name' => 'daily-sale', 'screen' => 'Reports', 'action' => 'Daily Sale'],
    ['name' => 'monthly-sale', 'screen' => 'Reports', 'action' => 'Monthly Sale'],
    ['name' => 'daily-purchase', 'screen' => 'Reports', 'action' => 'Daily Purchase'],
    ['name' => 'monthly-purchase', 'screen' => 'Reports', 'action' => 'Monthly Purchase'],
    ['name' => 'payment-report', 'screen' => 'Reports', 'action' => 'Payment Report'],
    ['name' => 'warehouse-stock-report', 'screen' => 'Reports', 'action' => 'Warehouse Stock Report'],
    ['name' => 'supplier-report', 'screen' => 'Reports', 'action' => 'Supplier Report'],
    ['name' => 'sale-report', 'screen' => 'Reports', 'action' => 'Sale Report'],
    ['name' => 'customer-report', 'screen' => 'Reports', 'action' => 'Customer Report'],
    ['name' => 'product-report', 'screen' => 'Reports', 'action' => 'Product Report'],
    ['name' => 'purchase-report', 'screen' => 'Reports', 'action' => 'Purchase Report'],
    ['name' => 'sale-report-chart', 'screen' => 'Reports', 'action' => 'Sale Report Chart'],
    ['name' => 'warehouse-report', 'screen' => 'Reports', 'action' => 'Warehouse Report'],
    ['name' => 'warehouse-stock-report', 'screen' => 'Reports', 'action' => 'Warehouse Stock Report'],
    ['name' => 'user-report', 'screen' => 'Reports', 'action' => 'User Report'],
    ['name' => 'supplier-due-report', 'screen' => 'Reports', 'action' => 'Supplier Due Report'],
    ['name' => 'due-report', 'screen' => 'Reports', 'action' => 'Due Report'],
    ['name' => 'all_notification', 'screen' => 'Notifications', 'action' => 'All Notifications'],
    ['name' => 'send_notification', 'screen' => 'Notifications', 'action' => 'Send Notifications'],
    ['name' => 'unit', 'screen' => 'Unit', 'action' => 'Index'],
    ['name' => 'currency', 'screen' => 'Currency', 'action' => 'Index'],
    ['name' => 'tax', 'screen' => 'Tax', 'action' => 'Index'],
    ['name' => 'general_setting', 'screen' => 'Settings', 'action' => 'General Setting'],
    ['name' => 'category', 'screen' => 'Category', 'action' => 'Index'],
    ['name' => 'delivery', 'screen' => 'Delivery', 'action' => 'Index'],
    ['name' => 'today_sale', 'screen' => 'Reports', 'action' => 'Today Sale'],
    ['name' => 'today_profit', 'screen' => 'Reports', 'action' => 'Today Profit'],
    ['name' => 'adjustment', 'screen' => 'Adjustment', 'action' => 'Index'],
          ];



        // Seeding the permissions
        foreach ($notifications as $notification) {
            $this->SeedNotification($notification['name'], $notification['screen'], $notification['action']);
        }
    }

    /**
     * Seed individual notification
     */
    public function SeedNotification($notification, $screen, $action)
{
    if (!NotificationScreen::where('name', $notification)->exists()) {
        $notifications = new NotificationScreen();
        $notifications->name = $notification;
        $notifications->screen = $screen;
        $notifications->action = $action;
        $notifications->save();
    }
}
}
