<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            'Quotation List',
            'Membership Preview',
            'Quotation Create',
            'Quotation Edit',
            'Quotation Verify',
            'Quotation View',
            'Quotation Delete',
            'Order List',
            'Order Create',
            'Order Edit',
            'Order View',
            'Order Delete',
            'Category List',
            'Category Create',
            'Category Edit',
            'Category View',
            'Category Delete',
            'Sales Price List',
            'Sales Price Create',
            'Sales Price Edit',
            'Sales Price Verify',
            'Sales Price View',
            'Sales Price Delete',
            'Invoice List',
            'Invoice Create',
            'Invoice Edit',
            'Invoice View',
            'Invoice Preview',
            'Invoice Delete',
            'Machine Status View',
            'Shopfloor View',
            'Production Output Traceability List',
            'Production Output Traceability Edit',
            'Production Output Traceability QC',
            'Production Output Traceability View',
            'Summary Report View',
            'Call For Assistance List',
            'Call For Assistance Update',
            'Call For Assistance View',
            'OEE Report View',
            'Inventory Shopfloor View',
            'Inventory Dashboard View',
            'Good Receiving List',
            'Good Receiving Create',
            'Good Receiving Edit',
            'Good Receiving Receive',
            'Good Receiving QC',
            'Good Receiving Approve',
            'Good Receiving Allocation',
            'Good Receiving View',
            'Good Receiving Delete',
            'Delivery Instruction List',
            'Delivery Instruction Create',
            'Delivery Instruction Edit',
            'Delivery Instruction View',
            'Delivery Instruction Delete',
            'Stock Adjustment List',
            'Stock Adjustment Update',
            'Stock Relocation List',
            'Stock Relocation Create',
            'Stock Relocation Edit',
            'Stock Relocation View',
            'Stock Relocation Delete',
            'Product Reordering List',
            'Product Reordering Create',
            'Product Reordering Edit',
            'Product Reordering View',
            'Product Reordering Delete',
            'Outgoing List',
            'Outgoing Create',
            'Outgoing Edit',
            'Outgoing View',
            'Outgoing Preview',
            'Outgoing Delete',
            'Sales Return List',
            'Sales Return Create',
            'Sales Return Edit',
            'Sales Return View',
            'Sales Return Delete',
            'Purchase Return List',
            'Purchase Return Create',
            'Purchase Return Edit',
            'Purchase Return View',
            'Purchase Return Preview',
            'Purchase Return QC',
            'Purchase Return Receive',
            'Purchase Return Delete',
            'Inventory Report View',
            'Stock Card Report View',
            'Summary DO Report View',
            'Type Of Rejection List',
            'Type Of Rejection Create',
            'Type Of Rejection Edit',
            'Type Of Rejection View',
            'Type Of Rejection Delete',
            'Type Of Product List',
            'Type Of Product Create',
            'Type Of Product Edit',
            'Type Of Product View',
            'Type Of Product Delete',
            'Machine Tonnage List',
            'Machine Tonnage Create',
            'Machine Tonnage Edit',
            'Machine Tonnage View',
            'Machine Tonnage Delete',
            'Machine List',
            'Machine Create',
            'Machine Edit',
            'Machine View',
            'Machine Delete',
            'Area List',
            'Area Create',
            'Area Edit',
            'Area View',
            'Area Delete',
            'Area Rack List',
            'Area Rack Create',
            'Area Rack Edit',
            'Area Rack View',
            'Area Rack Delete',
            'Area Level List',
            'Area Level Create',
            'Area Level Edit',
            'Area Level View',
            'Area Level Delete',
            'Unit List',
            'Unit Create',
            'Unit Edit',
            'Unit View',
            'Unit Delete',
            'Process List',
            'Process Create',
            'Process Edit',
            'Process View',
            'Process Delete',
            'Customer List',
            'Customer Create',
            'Customer Edit',
            'Customer View',
            'Customer Delete',
            'Supplier List',
            'Supplier Create',
            'Supplier Edit',
            'Supplier View',
            'Supplier Delete',
            'Product List',
            'Product Create',
            'Product Edit',
            'Product View',
            'Product Delete',
            'Product Amortization Edit',
            'Department List',
            'Department Create',
            'Department Edit',
            'Department View',
            'Department Delete',
            'Designation List',
            'Designation Create',
            'Designation Edit',
            'Designation View',
            'Designation Delete',
            'Role List',
            'Role Create',
            'Role Edit',
            'Role View',
            'Role Delete',
            'User List',
            'User Create',
            'User Edit',
            'User View',
            'User Delete',
            'Leave List',
            'Leave Create',
            'Leave Edit',
            'Leave View',
            'Leave Manage',
            'Leave Delete',
            'General Settings SST Percentage',
            'General Settings PO Important Note',
            'General Settings Spec Break',
            'General Settings Initial Ref No',
            'General Settings PR Approval',
            'Purchase Price List',
            'Purchase Price Create',
            'Purchase Price Edit',
            'Purchase Price Verify',
            'Purchase Price View',
            'Purchase Price Delete',
            'Purchase Requisition List',
            'Purchase Requisition Create',
            'Purchase Requisition Edit',
            'Purchase Requisition View',
            'Purchase Requisition Delete',
            'Purchase Requisition Verify HOD',
            'Purchase Requisition Verify ACC',
            'Purchase Requisition Approve',
            'Purchase Requisition Decline',
            'Purchase Requisition Cancel',
            'Purchase Planning List',
            'Purchase Planning Create',
            'Purchase Planning Edit',
            'Purchase Planning View',
            'Purchase Planning Delete',
            'Purchase Planning Verify HOD',
            'Purchase Planning Verify ACC',
            'Purchase Planning Approve',
            'Purchase Planning Check',
            'Purchase Planning Decline',
            'Purchase Planning Cancel',
            'Purchase Order List',
            'Purchase Order Create',
            'Purchase Order Edit',
            'Purchase Order View',
            'Purchase Order Preview',
            'Purchase Order Delete',
            'Purchase Order Verify',
            'Purchase Order Check',
            'Purchase Order Decline',
            'Purchase Order Cancel',
            'Supplier Ranking List',
            'Supplier Ranking Create',
            'Supplier Ranking Edit',
            'Supplier Ranking View',
            'Supplier Ranking Delete',
            'BOM List',
            'BOM Create',
            'BOM Edit',
            'BOM View',
            'BOM Delete',
            'BOM Verification',
            'BOM Verify',
            'BOM Decline',
            'BOM Cancel',
            'BOM Inactive',
            'BOM Report',
            'Daily Production Planning List',
            'Daily Production Planning Create',
            'Daily Production Planning Edit',
            'Daily Production Planning View',
            'Daily Production Planning Delete',
            'Monthly Production Planning',
            'Production Scheduling View',
            'Material Requisition List',
            'Material Requisition Create',
            'Material Requisition Edit',
            'Material Requisition View',
            'Material Requisition Delete',
            'Material Requisition Issue',
            'Material Requisition Receive',
            'Transfer Request List',
            'Transfer Request Create',
            'Transfer Request Edit',
            'Transfer Request View',
            'Transfer Request Delete',
            'Transfer Request Issue',
            'Transfer Request Receive',
            'Transfer Request QC',
            'Discrepancy List',
            'Discrepancy Edit',
            'Discrepancy View',
            'Attendance List',
            'Attendance Import',
            'Attendance Export',
            'General Settings Payroll Setup',
            'Summary Attendence List',
            'Payroll List',
            'Payroll Create',
        ];


        $accountingPermissions = [
            'Account Dashboard',
            'Account Category List',
            'Account Category Create',
            'Account Category Edit',
            'Account Category View',
            'Account Category Delete',
            'Account List',
            'Account Create',
            'Account Ledger List',
            'Account Transaction Create',
            'Account Reconcile List',
            'Ledger List',
            'Trial Balance List',
            'Carryforward List',
            'Profit Loss List',
            'Balance Sheet List',
            'Aging Report List',
        ];

        foreach ($permissions as $permission) {
            if (!Permission::where('name', $permission)->exists()) {
                Permission::create(['name' => $permission]);
            }
        }


        foreach ($accountingPermissions as $accountingPermission) {
            if (!Permission::where('name', $accountingPermission)->exists()) {
                Permission::create(['name' => $accountingPermission]);
            }
        }
    }
}
